version: "2"
services:
  server:
    image: prom/prometheus:v2.31.0
    container_name: prometheus-server
    command:
      - --storage.tsdb.retention.time=15d
      - --config.file=/etc/config/prometheus.yml
      - --storage.tsdb.path=/data
      - --web.console.libraries=/etc/prometheus/console_libraries
      - --web.console.templates=/etc/prometheus/consoles
      - --web.enable-lifecycle
    volumes:
      - ./conf/prometheus:/etc/config
      - ./data/prometheus:/data
    ports:
      - "9090:9090"
    restart: always

  pushgateway:
    container_name: prometheus-pushgateway
    image: prom/pushgateway:v1.4.2
    ports:
      - "9091:9091"
    volumes:
      - ./conf:/etc/config
      - ./data/pushgateway:/data
    env_file:
      - ./env/pushgateway.env
    restart: always

  grafana:
    container_name: grafana
    image: grafana/grafana:8.2.3
    ports:
      - 3000:3000
    user: '104'
    volumes:
      - ./conf:/etc/config
      - ./data/grafana:/var/lib/grafana/
    env_file:
      - ./env/grafana.env
    restart: always