version: '2'
services:
  debezium-connect:
    container_name: debezium-connect
    hostname: debezium-connect
    image: hub.d.cisdigital.cn/debezium/connect:1.7
    ports:
      - 8083:8083
      - 1976:1976
      - 8088:8088
    volumes:
      - ./logs:/kafka/logs
      - ./agent:/kafka/etc
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=rick_connect_configs
      - OFFSET_STORAGE_TOPIC=rick_connect_offsets
      - STATUS_STORAGE_TOPIC=rick_connect_statuses
      - KAFKA_OPTS=-javaagent:/kafka/etc/jmx_prometheus_javaagent-0.16.1.jar=8088:/kafka/etc/config.yml
      - JMXHOST=localhost
      - JMXPORT=1976
    extra_hosts:
      - "kafka:10.75.20.212"
      - "zookeeper:10.75.20.212"
