version: '3.1'
services:
  db:
    image: mysql:8.0.27
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
     - 3309:3306
    environment:
     - MYSQL_ROOT_PASSWORD=debezium
    volumes:
      - ./data:/var/lib/mysql