version: '2'
networks:
  kafka:
    driver: bridge

services:
  zookeeper:
    image: 'bitnami/zookeeper:3.7.0'
    container_name: zookeeper
    hostname: zookeeper
    volumes:
      - ./data:/bitnami/zookeeper/data
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    networks:
      - kafka

  kafka:
    image: 'bitnami/kafka:2.8.1'
    container_name: kafka
    hostname: kafka
    volumes:
      - ./agent:/bitnami/kafka/config
      - ./data:/bitnami/kafka/data
    ports:
     - 9092:9092
     - 8089:8089
    environment:
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OPTS: "-javaagent:/bitnami/kafka/config/jmx_prometheus_javaagent-0.16.1.jar=8089:/bitnami/kafka/config/config.yml"
    networks:
      - kafka